### ISSUE TITLE
.close not closing

### ISSUE THREAD

**Issue by c0debreaker** [DrBenton/Node-DBI#26]
Hi,

I have this nodejs code. I execute it by running node app.js. I'll get the results on the screen but it doesn't go back to the prompt. Am I missing a code?

var DBWrapper = require('node-dbi').DBWrapper;
var dbConnectionConfig = { host: 'localhost:5432', user: 'ubuntu', password: 'password', database: 'warehouse' };

dbWrapper = new DBWrapper( 'pg', dbConnectionConfig );
dbWrapper.connect();

dbWrapper.fetchAll('SELECT \* FROM teamsaturn.devices', null, function(err, result) {
    if (!err) {
            console.log(result);
    } else {
           console.log(err);
    }
});

dbWrapper.close( function(err) {console.log('Connection closed !');} );

**Comment by elnoxgdl** [comment]
Hi,

That's correct I'm facing the same problem while calling .close() it doesn't seem to do anything.
This is an old thread but still happening...

**Comment by c0debreaker** [comment]
I'm closing this ticket. I may have used a different solution.
